// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetClipboardHistory():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function SetValueToClipboard(arg1:string):Promise<void>;
