// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetClipboardHistory() {
  return window['go']['main']['App']['GetClipboardHistory']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetValueToClipboard(arg1) {
  return window['go']['main']['App']['SetValueToClipboard'](arg1);
}
